# Example stellar.toml

NETWORK_PASSPHRASE="Test SDF Network ; September 2015" # Use the testnet passphrase for testing
VERSION="1.0.0"

# ISSUER INFORMATION
FEDERATION_SERVER="https://localhost:3000/federation"
AUTH_SERVER="https://localhost:3000/auth"
TRANSFER_SERVER="https://localhost:3000/transfer"
ACCOUNTS=[
    "GISSUERACCOUNTPUBLICKEY" # Replace with your issuer account's public key
]
ORG_NAME="Your Organization Name"
ORG_URL="https://localhost:3000"
ORG_LOGO="https://localhost:3000/logo.png" # Update with a local image URL if needed
ORG_DESCRIPTION="Description of your organization and its mission"
ORG_PHYSICAL_ADDRESS="123 Main Street, Anytown, Country"
ORG_TWITTER="yourorg"
ORG_GITHUB="yourorg"

# ASSET DETAILS
[[CURRENCIES]]
code="ENTRYXX10001"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
conditions="EntryX is a digital ticket for events and concerts."
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRY0010003"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
conditions="EntryX is a digital ticket for events and concerts."
image="https://entryx.me/entryx.png"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="TIXGeneralAd"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
conditions="EntryX is a digital ticket for events and concerts."
image="entryx.me/entryx.png"
fixed_number=1000000
max_number=10000000


[[CURRENCIES]]
code="ENTRYXX10004"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
conditions="EntryX is a digital ticket for events and concerts."
image="www.entryx.me/entryx.png"
fixed_number=1000000
max_number=10000000
