# Example stellar.toml

NETWORK_PASSPHRASE="Test SDF Network ; September 2015" # Use the testnet passphrase for testing
VERSION="1.0.0"

# ISSUER INFORMATION
FEDERATION_SERVER="https://localhost:3000/federation"
AUTH_SERVER="https://localhost:3000/auth"
TRANSFER_SERVER="https://localhost:3000/transfer"
ACCOUNTS=[
    "GISSUERACCOUNTPUBLICKEY" # Replace with your issuer account's public key
]
ORG_NAME="Your Organization Name"
ORG_URL="https://localhost:3000"
ORG_LOGO="https://localhost:3000/logo.png" # Update with a local image URL if needed
ORG_DESCRIPTION="EntryX is a decentralized ticketing platform"
ORG_PHYSICAL_ADDRESS="Guadalajara, Jalisco, Mexico"
ORG_GITHUB="https://github.com/JoseCToscano"

# ASSET DETAILS
[[CURRENCIES]]
code="ENTRYXX10001"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRY0010002"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX10002"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX10003"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000


[[CURRENCIES]]
code="ENTRYXX10004"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX10005"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX10006"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX10007"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX10008"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX10009"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX10010"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX10011"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX10012"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX10013"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20001"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20002"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20003"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000


[[CURRENCIES]]
code="ENTRYXX20004"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20005"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20006"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20007"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20008"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20009"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20010"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20011"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20012"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX20013"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Ticket Entry"
desc="EntryX is a decentralized ticketing platform"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXXC0001"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Acoustic Starry Night"
desc="EntryX's ticket for Acoustic Starry Night"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX50001"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Meridian 2024"
desc="EntryX's ticket for Meridian 2024: Early Bird"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX50002"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Meridian 2024"
desc="EntryX's ticket for Meridian 2024: General Access"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX50003"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Meridian 2024"
desc="EntryX's ticket for Meridian 2024: VIP Experience"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX60001"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Blockchain & Beers"
desc="EntryX's ticket for Blockchain & Beers"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000

[[CURRENCIES]]
code="ENTRYXX60001"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Digital Art Fair"
desc="EntryX's ticket for Digital Art Fair: General Access"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000


[[CURRENCIES]]
code="ENTRYXX80001"
issuer="GCUKFNNR35HDXU5GPFPMVTVWKNHFP7KK2VRWP7PJBZB2RKKXXWLALXIH"
status="live"
display_decimals=2
name="Quantum Computing Conference"
desc="EntryX's ticket for Quantum Computing Conference: 3 Day pass"
conditions="Decentralized Ticket Entry"
desc="Decentralized Ticket Entry"
image="https://entryx.me/entryx-icon.svg"
fixed_number=1000000
max_number=10000000
