export const MAX_UNITS_PER_PURCHASE = 10;

export const MAX_UNITS_PER_ACCOUNT = 20;

export const Fees = {
  SELLER_PUBLISHING_FEE: 500,
  SELLER_UNITARY_COMMISSION_PERCENTAGE: 1,
  RESELLER_PUBLISHING_FEE: 20,
  RESELLER_UNITARY_COMMISSION_PERCENTAGE: 5,
  SERVICE_FEE: 10,
};
